Models/Leave.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Leave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leave()
        {
            this.payroles = new HashSet<payrole>();
            this.empreturnfromleavesubs = new HashSet<empreturnfromleavesub>();
        }

        [Display(Name = "Employee ID")]
        public int Employee_id { get; set; }

        public int Id { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public System.DateTime Date { get; set; }

        public string Reference { get; set; }

        [Display(Name = "from")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> Start_leave { get; set; }

        [Display(Name = "to")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> End_leave { get; set; }

        [Display(Name = "Return leave")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> Return_leave { get; set; }

        [Display(Name = "leave type")]
        public string leave_type { get; set; }

        [Display(Name = "actual_return_date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> actual_return_date { get; set; }

        public Nullable<double> toltal_requested_days { get; set; }

        public Nullable<bool> leave_salary { get; set; }

        public Nullable<long> mobile_no { get; set; }

        public string email { get; set; }

        public Nullable<double> leave_bal { get; set; }

        public string submitted_by { get; set; }

        public string approved_by { get; set; }

        public Nullable<System.DateTime> time { get; set; }

        public Nullable<int> days { get; set; }

        public string data_o_n { get; set; }

        [Display(Name = "is half-day included")]
        public bool half { get; set; }
        public string actualchangedby { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> actualchangeddateby { get; set; }
        public string approved_byHR { get; set; }
        public string apstatus { get; set; }
        public string imgpath { get; set; }
    
        public virtual master_file master_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payrole> payroles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empreturnfromleavesub> empreturnfromleavesubs { get; set; }
    }
}

Controllers/LeavesController.cs
using System.Data.Entity.Infrastructure;

namespace HRworks.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.UI.WebControls;
    using System.Data;
    using HRworks.Models;
    using Microsoft.Ajax.Utilities;
    using OfficeOpenXml;
    using PagedList;
    using static Humanizer.On;
    using static Microsoft.Isam.Esent.Interop.EnumeratedColumn;
    using System.Collections;
    using System.Windows.Shell;

    [Authorize]
    public class LeavesController : Controller
    {
        private readonly HREntities db = new HREntities();
        private readonly biometrics_DBEntities db2 = new biometrics_DBEntities();
        private readonly LogisticsSoftEntities db3 = new LogisticsSoftEntities();


        // GET: Leaves/Create               
        public ActionResult Create()
        {
            var listItems = new List<ListItem>
            {
                new ListItem { Text = "Annual", Value = "1" },
                new ListItem { Text = "Sick(non industrial)", Value = "2" },
                new ListItem { Text = "Compassionate", Value = "3" },
                new ListItem { Text = "Maternity", Value = "4" },
                new ListItem { Text = "Haj", Value = "5" },
                new ListItem { Text = "Unpaid", Value = "6" },
                new ListItem { Text = "Sick(industrial)", Value = "7" },
                new ListItem { Text = "UDDAH", Value = "8" },
                new ListItem { Text = "ESCORT", Value = "9" },
                new ListItem { Text = "PATERNITY ", Value = "10" },
                new ListItem { Text = "SABBATICAL", Value = "11" },
                new ListItem { Text = "STUDY LEAVE ", Value = "12" },
                new ListItem { Text = "Compensatory", Value = "13" },
                new ListItem { Text = "balance rectification", Value = "14" }
            };
            this.ViewBag.leave_type = new SelectList(listItems, "Value", "Text");/*
            var alist = this.db.master_file.OrderBy(e => e.employee_no).ThenByDescending(x => x.date_changed).ToList();
            var afinallist = new List<master_file>();
            foreach (var file in alist)
            {
                if (afinallist.Count == 0) afinallist.Add(file);

                if (!afinallist.Exists(x => x.employee_no == file.employee_no)) afinallist.Add(file);
            }
            */
            var mancaon = new master_fileController();
            var afinallist = mancaon.emplist();
            this.ViewBag.employee_id = new SelectList(
                afinallist.OrderBy(x => x.employee_no),
                "employee_id",
                "emiid");
            ViewBag.employee_id1 = new SelectList(
                afinallist.OrderBy(e => e.employee_name),
                "employee_id",
                "employee_name");
            return this.View();
        }

        // POST: Leaves/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(
                Include =
                    "Employee_id,Id,Date,Reference,Start_leave,End_leave,Return_leave,days,leave_type,actual_return_date,half")]
            Leave leave,
            HttpPostedFileBase fileBase)
        {
            var listItems = new List<ListItem>
            {
                new ListItem { Text = "Annual", Value = "1" },
                new ListItem { Text = "Sick(non industrial)", Value = "2" },
                new ListItem { Text = "Compassionate", Value = "3" },
                new ListItem { Text = "Maternity", Value = "4" },
                new ListItem { Text = "Haj", Value = "5" },
                new ListItem { Text = "Unpaid", Value = "6" },
                new ListItem { Text = "Sick(industrial)", Value = "7" },
                new ListItem { Text = "UDDAH", Value = "8" },
                new ListItem { Text = "ESCORT", Value = "9" },
                new ListItem { Text = "PATERNITY ", Value = "10" },
                new ListItem { Text = "SABBATICAL", Value = "11" },
                new ListItem { Text = "STUDY LEAVE ", Value = "12" },
                new ListItem { Text = "Compensatory", Value = "13" },
                new ListItem { Text = "balance rectification", Value = "14" }
            };
            var mancaon = new master_fileController();
            var afinallist = mancaon.emplist();
            this.ViewBag.employee_id = new SelectList(
                afinallist.OrderBy(x => x.employee_no),
                "employee_id",
                "emiid");
            ViewBag.employee_id1 = new SelectList(
                afinallist.OrderBy(e => e.employee_name),
                "employee_id",
                "employee_name");
            var leaveid = afinallist.Find(x => x.employee_id == leave.Employee_id);
            var jd = leaveid.date_joined;
            this.ViewBag.leave_type = new SelectList(listItems, "Value", "Text");
            string serverfile;
            var leavelistc = this.db.Leaves.ToList();
            if (leavelistc.Exists(x =>
                    ((x.Start_leave <= leave.Start_leave && x.End_leave >= leave.Start_leave) ||
                     (x.Start_leave <= leave.End_leave && x.End_leave >= leave.End_leave)) &&
                    x.Employee_id == leave.Employee_id))
            {
                ModelState.AddModelError("Start_leave", "already exists");

                goto jderr;
            }

            if (leavelistc.Exists(x =>
                    (x.Start_leave >= leave.Start_leave && x.End_leave <= leave.End_leave) &&
                    x.Employee_id == leave.Employee_id))
            {
                ModelState.AddModelError("Start_leave", "already exists");

                goto jderr;
            }


            //            if (leavelistc.Exists(x=>x.End_leave >= leave.Start_leave && x.Employee_id == leave.Employee_id))
            //            {
            //                ModelState.AddModelError("Start_leave", leave.Start_leave+" already exists");
            //
            //                goto jderr;
            //            }
            if (leave.Start_leave < jd && leave.Start_leave != default)
            {
                ModelState.AddModelError("Start_leave", "selected date is before " + jd);
                goto jderr;
            }

            if (leave.End_leave < jd && leave.End_leave != default)
            {
                ModelState.AddModelError("Start_leave", "selected date is before " + jd);
                goto jderr;
            }

            if (leave.End_leave < leave.Start_leave)
            {
                ModelState.AddModelError("Start_leave", "cannot add date in reverse");
                goto jderr;
            }


            if (leave.leave_type == "5")
            {
                var datediff = (leave.End_leave - leave.Start_leave).Value.TotalDays + 1;
                if (datediff > 10)
                {
                    ModelState.AddModelError("leave_type", "maximum days allowed for haj are 10 ");
                    goto jderr;
                }

                if (leavelistc.Exists(x => x.leave_type == "5" && x.Employee_id == leave.Employee_id))
                {
                    ModelState.AddModelError("leave_type", "already taken once");
                    goto jderr;
                }
            }

            var leavelist = this.db.Leaves.ToList();
            if (leavelist.Exists(
                    x => x.Employee_id == leave.Employee_id && x.Start_leave == leave.Start_leave
                                                            && x.End_leave == leave.End_leave))
            {
                ViewBag.exhist = "the entry already exists";
                return this.View(leave);
            }

            if (fileBase != null)
            {
                var i = 0;
                var imgname = Path.GetFileName(fileBase.FileName);
                var fileexe = Path.GetExtension(fileBase.FileName);
                var filepath = new DirectoryInfo("D:/HR/leave/");
                serverfile =
                    "D:/HR/leave/" + leave.master_file.employee_no; /*+ "/"+ passport.employee_no + fileexe;*/
                filepath = Directory.CreateDirectory(serverfile);
                do
                {
                    serverfile = "D:/HR/leave/" + leave.master_file.employee_no + "/" +
                                 leave.master_file.employee_no + "_(" + i + ")_" + DateTime.Now.ToString("dd-MM-YY") +
                                 fileexe;
                    i++;
                } while (System.IO.File.Exists(
                             serverfile = "D:/HR/leave/" + leave.master_file.employee_no + "/" +
                                          leave.master_file.employee_no + "_(" + i + ")_" +
                                          DateTime.Now.ToString("dd-MM-YY") +
                                          fileexe));

                fileBase.SaveAs(serverfile);
            }
            else
            {
                serverfile = null;
            }

            ViewBag.exhist = "";
            if (this.ModelState.IsValid)
            {
                var file1 = new Leave();
                file1.Employee_id = leave.Employee_id;
                var masterstatus = this.db.master_file.Find(leave.Employee_id);
                file1.Date = leave.Date;
                file1.Reference = serverfile;
                file1.half = leave.half;
                file1.Start_leave = leave.Start_leave;
                file1.End_leave = leave.End_leave;
                if (leave.Return_leave == null)
                {

Views/Leaves/Create.cshtml
@model HRworks.Models.Leave

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.14.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(function () {
        $("#datepicker").datepicker({
            altField: "#alternate",
            altFormat: "MM,yy",
            changeMonth: true,
            changeYear: true,
            showOtherMonths: true,
            selectOtherMonths: true,
            showButtonPanel: true,
            dateFormat: "dd M yy"
        });
        $("#datepicker1").datepicker({
            altField: "#alternate",
            altFormat: "MM,yy",
            changeMonth: true,
            changeYear: true,
            showOtherMonths: true,
            selectOtherMonths: true,
            showButtonPanel: true,
            dateFormat: "dd M yy"
        });
        $("#datepicker2").datepicker({
            altField: "#alternate",
            altFormat: "MM,yy",
            changeMonth: true,
            changeYear: true,
            showOtherMonths: true,
            selectOtherMonths: true,
            showButtonPanel: true,
            dateFormat: "dd M yy"
        });
        $("#datepicker3").datepicker({
            altField: "#alternate",
            altFormat: "MM,yy",
            changeMonth: true,
            changeYear: true,
            showOtherMonths: true,
            selectOtherMonths: true,
            showButtonPanel: true,
            dateFormat: "dd M yy",
            onSelect: function (date) {

                var selectedDate = new Date(date);
                var msecsInADay = 86400000;
                var endDate = new Date(selectedDate.getTime() + msecsInADay);

                //Set Minimum Date of EndDatePicker After Selected Date of StartDatePicker
                $("#datepicker2").datepicker("option", "minDate", endDate);
            }
        });
        $("#datepicker4").datepicker({
            altField: "#alternate",
            altFormat: "MM,yy",
            changeMonth: true,
            changeYear: true,
            showOtherMonths: true,
            selectOtherMonths: true,
            showButtonPanel: true,
            dateFormat: "dd M yy",
            onSelect: function (date) {

                var selectedDate = new Date(date);
                var msecsInADay = 86400000;
                var endDate = new Date(selectedDate.getTime() );

                //Set Minimum Date of EndDatePicker After Selected Date of StartDatePicker
                $("#datepicker3").datepicker("option", "minDate", endDate);
            }
        });
        $("#employee_no").chosen({ no_results_text: "Oops, nothing found!" });
    });

    function dayscount() {
        var a = new Date($("#datepicker3").val());
        var b = new Date($("#datepicker4").val());
        if ((a - b) == 0) {
            $("#days").val(1);
        } else {
        $("#days").val((a - b) / (1000 * 60 * 60 * 24)+1);
        }
    }
</script>
<script>
    function byidfill(parameters) {
        var filled = document.getElementById('fill');
        document.getElementById('hide2').style.display = "none";
        var x = document.getElementById("employee_no1");
        var y = document.getElementById("employee_no");
        y.value = x.value;
        document.getElementById('hide').style.display = "";
        var z = document.getElementById("demo");
        var w = document.getElementById("demo1");
        z.style.display = "";
        w.style.display = "none";
        myFunction();
    };

    function bynamefill(parameters) {
        document.getElementById('hide2').style.display = "";
        var x = document.getElementById("employee_no1");
        var y = document.getElementById("employee_no");
        x.value = y.value;
        document.getElementById('hide').style.display = "none";
        var z = document.getElementById("demo");
        var w = document.getElementById("demo1");
        w.style.display = "";
        z.style.display = "none";
        myFunction1();
    };

//        var loadfile = function (event) {
//            var reader = new FileReader();
//            reader.onload = function () {
//                var output = document.getElementById('output');
//                output.src = reader.result;
//            };
//            reader.readAsDataURL(event.target.files[0]);
//        };

    function myFunction() {
        var x = document.getElementById("employee_no").value;
        document.getElementById("demo").innerHTML = "employee_id :" + x;

    };

    function myFunction1() {
        var x = document.getElementById("employee_no1").value;
        document.getElementById("demo1").innerHTML = "employee_id :" + x;

    };
</script>

@using (Html.BeginForm("Create", "Leaves", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal" onclick="dayscount()">
    <h2>New Leave</h2>
    <hr /><p style="font-size: 110%; color: red">@ViewBag.exhist</p>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Employee_id, "employee_no", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6"
             id="hide">
            @*
                        @Html.DropDownList("employee_no", null, htmlAttributes: new { @class = "form-control", @onchange="myfunction();" ,@id="employee_no"})*@
            @Html.DropDownList("Employee_id", null, new { @class = "form-control", @id = "employee_no" })
            @Html.ValidationMessageFor(model => model.Employee_id, "", new { @class = "text-danger" })

        </div>
        <div class="col-md-6"
             id="hide2"
             style="display: none">
            @*
                        @Html.DropDownList("employee_no", null, htmlAttributes: new { @class = "form-control", @onchange="myfunction();" ,@id="employee_no"})*@
            @Html.DropDownList("employee_id1", null, new { @class = "form-control", @id = "employee_no1" })
            @Html.ValidationMessageFor(model => model.Employee_id, "", new { @class = "text-danger" })

        </div>

        <div class="col-md-4">
            <input type="button"
                   onclick="bynamefill()" @*ondblclick="byidfill()"*@
                   value="change to name"
                   id="demo"/>
        </div>
        <div class="col-md-4">
            <input type="button"
                   onclick="byidfill()"
                   value="change to id"
                   style="display: none"
                   id="demo1"/>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            *@
            <input type="text"
                   id="datepicker"
                   class="form-control"
                   name="Date" required="required"/>
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.Reference, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*
                @Html.EditorFor(model => model.Reference, new { htmlAttributes = new { @class = "form-control" } })
            *@
            <input type="file"
                   id="fileBase"
                   name="fileBase"  accept="image/*,.pdf,.doc"/>
            @Html.ValidationMessageFor(model => model.Reference, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Start_leave, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*
                @Html.EditorFor(model => model.Start_leave, new { htmlAttributes = new { @class = "form-control" } })
            *@
            <input type="text"
                   id="datepicker4"
                   class="form-control"
                   name="Start_leave"  required="required"/>
            @Html.ValidationMessageFor(model => model.Start_leave, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.End_leave, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*
                @Html.EditorFor(model => model.End_leave, new { htmlAttributes = new { @class = "form-control" } })
            *@
            <input type="text"
                   id="datepicker3"
                   class="form-control"
                   name="End_leave"  required="required"/>
            @Html.ValidationMessageFor(model => model.End_leave, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.days, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.days, new { htmlAttributes = new { @class = "form-control", @id = "days" } })
            @Html.ValidationMessageFor(model => model.days, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.Return_leave, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*
                @Html.EditorFor(model => model.Return_leave, new { htmlAttributes = new { @class = "form-control" } })
            *@
            <input type="text"
                   id="datepicker2"
                   class="form-control"
                   name="Return_leave"  required="required"/>
            @Html.ValidationMessageFor(model => model.Return_leave, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.leave_type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*
                @Html.EditorFor(model => model.leave_type, new { htmlAttributes = new { @class = "form-control" } })
            *@
            @Html.DropDownList("leave_type", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.leave_type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="display: none">
        @Html.LabelFor(model => model.actual_return_date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*
                @Html.EditorFor(model => model.actual_return_date, new { htmlAttributes = new {  @id="datepicker",@class = "form-control"} })
            *@
            <input type="text"
                   id="datepicker1"
                   class="form-control"
                   name="actual_return_date" />
            @Html.ValidationMessageFor(model => model.actual_return_date, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.half, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(m => m.half)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" onclick="dayscount()">
            <input type="submit" value="Save" class="btn btn-default" onclick="dayscount()" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Leaves/Details.cshtml
@model HRworks.Models.Leave

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Leave</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start_leave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start_leave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End_leave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End_leave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Return_leave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Return_leave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.leave_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.leave_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.actual_return_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actual_return_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.master_file.employee_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.master_file.employee_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.master_file.employee_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.master_file.employee_no)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Leaves/Importexcel.cshtml
@using System.Data;
@{
    ViewBag.Title = "ImportExcel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ImportExcel</h2>
<!--[if !IE]><!-->
<style type="text/css">


    /* Generic Styling, for Desktops/Laptops */
    table {
        width: 100%;
        border-collapse: collapse;
    }
    /* Zebra striping */
    tr:nth-of-type(odd) {
        background: #eee;
    }

    th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    td, th {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }
    /*
    Max width before this PARTICULAR table gets nasty
    This query will take effect for any screen smaller than 760px
    and also iPads specifically.
    */
    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        /* Force table to not be like tables anymore */
        table, thead, tbody, th, td, tr {
            display: block;
        }
            /* Hide table headers (but not display: none;, for accessibility) */
            thead tr {
                position: absolute;
                top: -9999px;
                left: -9999px;
            }

        tr {
            border: 1px solid #ccc;
        }

        td {
            /* Behave  like a "row" */
            border: none;
            border-bottom: 1px solid #eee;
            position: relative;
            padding-left: 50%;
        }

            td:before {
                /* Now like a table header */
                position: absolute;
                /* Top/left values mimic padding */
                top: 6px;
                left: 6px;
                width: 45%;
                padding-right: 10px;
                white-space: nowrap;
            }
            /*
     Label the data
     */
            td:before {
                content: attr(data-title);
            }
    }
</style>

<!--<![endif]-->
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("leave_absence_Index")'" value=" Absence Report"/>
<br/>
@using (Html.BeginForm("ImportExcel", "Leaves", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    <table>
        <tr><td>Excel file</td><td><input type="file" id="FileUpload1" name="FileUpload1" /></td></tr>
        <tr><td></td><td><input type="submit" id="Submit" name="Submit" value="Submit" /></td></tr>
    </table>
}

<div>
    <table id="">

        @if (ViewBag.Data != null)
        {
            <thead>

                @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                {
                <th>@column.ColumnName.ToUpper()</th>





            }
                </thead>
                if ((ViewBag.Data as System.Data.DataTable).Rows.Count > 0)
                {
                    foreach (DataRow dr in (ViewBag.Data as System.Data.DataTable).Rows)
                    {

                        <tr>

                            @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                            {
                                <td data-title='@column.ColumnName'>

                                    @dr[column].ToString()
                                </td>

                            }




                        </tr>



                    }

                }
                else
                {
                    int count = (ViewBag.Data as System.Data.DataTable).Columns.Count;
                    <tr>

                        <td colspan='@count' style="color:red;">

                            No Data Found.
                        </td>



                    </tr>



                }

            }
            else
            {
                if (ViewBag.Error != null)
                {
                    <tr>
                        <td style="color:red;">

                            @(ViewBag.Error != null ? ViewBag.Error.ToString() : "")
                        </td>



                    </tr>

                }
            }
    </table>
</div>