Models/visa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visa
    {
        [Display(Name = "employee id")]
        public int employee_id { get; set; }
        [Display(Name = "uid no")]
        public Nullable<long> uid_no { get; set; }
        [Display(Name = "file no")]
        public Nullable<long> file_no { get; set; }
        [Display(Name = "employee no")]
        public int emp_no { get; set; }
        [Display(Name = "place of issue")]
        public string place_of_issue { get; set; }
        [Display(Name = "accompanied by")]
        public string accompanied_by { get; set; }
        [Display(Name = "rv expiry")]
        public Nullable<System.DateTime> rv_expiry { get; set; }
        [Display(Name = "rv issue")]
        public Nullable<System.DateTime> rv_issue { get; set; }
        [Display(Name = "proff as per visa")]
        public string proff_as_per_visa { get; set; }
        [Display(Name = "imgpath")]
        public string imgpath { get; set; }
        public string sponsor { get; set; }
        [Display(Name = "changed by")]
        public string changed_by { get; set; }
        [Display(Name = "date changed")]
        public Nullable<System.DateTime> date_changed { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}

Controllers/visasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OfficeOpenXml;
using PagedList;
using HRworks.Models;

namespace HRworks.Controllers
{
    [Authorize]
    public class visasController : Controller
    {
        private HREntities db = new HREntities();

        public void DownloadExcel(string search)
        {
            List<visa> passexel = new List<visa>();
            List<visa> passexel1;
            if (search != null)
            {
                passexel1 = db.visas
                    .Where(
                        x => x.master_file.employee_name.Contains(search) /*.Contains(search) /*.StartsWith(search)*/)
                    .ToList();
            }
            else
            {
                passexel1 = db.visas.Include(p => p.master_file).ToList();
            }

            foreach (var a in passexel1.OrderBy(x => x.master_file.employee_no).ThenByDescending(y => y.date_changed))
            {
                if (!passexel.Exists(x => x.master_file.employee_no == a.master_file.employee_no))
                {
                    passexel.Add(a);
                }
            }
            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("visa".ToUpper());
            Sheet.Cells["A1"].Value = "employee no";
            Sheet.Cells["B1"].Value = "employee name";
            Sheet.Cells["C1"].Value = "file no";
            Sheet.Cells["D1"].Value = "uid no";
            Sheet.Cells["E1"].Value = "place of issue";
            Sheet.Cells["F1"].Value = "rv expiry";
            Sheet.Cells["G1"].Value = "lc expiry";
            Sheet.Cells["H1"].Value = "proff as per visa";
            Sheet.Cells["I1"].Value = "imgpath";
            Sheet.Cells["J1"].Value = "accompanied by";
            Sheet.Cells["K1"].Value = "sponsor";
            Sheet.Cells["L1"].Value = "changed by";
            Sheet.Cells["M1"].Value = "date_changed";
            int row = 2;
            foreach (var item in passexel)
            {
                Sheet.Cells[string.Format("A{0}", row)].Value = item.master_file.employee_no;
                Sheet.Cells[string.Format("B{0}", row)].Value = item.master_file.employee_name;
                Sheet.Cells[string.Format("C{0}", row)].Value = item.file_no;
                Sheet.Cells[string.Format("D{0}", row)].Value = item.uid_no;
                Sheet.Cells[string.Format("E{0}", row)].Value = item.place_of_issue;
                Sheet.Cells[string.Format("F{0}", row)].Value = item.rv_expiry;
                Sheet.Cells[string.Format("G{0}", row)].Value = item.rv_issue;
                Sheet.Cells[string.Format("H{0}", row)].Value = item.proff_as_per_visa;
                Sheet.Cells[string.Format("I{0}", row)].Value = item.imgpath;
                Sheet.Cells[string.Format("J{0}", row)].Value = item.accompanied_by;
                Sheet.Cells[string.Format("K{0}", row)].Value = item.sponsor;
                Sheet.Cells[string.Format("L{0}", row)].Value = item.changed_by;
                Sheet.Cells[string.Format("M{0}", row)].Value = item.date_changed;
                row++;
            }

            Sheet.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "filename =visa.xlsx");
            Response.BinaryWrite(Ep.GetAsByteArray());
            Response.End();
        }

        // GET: visas
        public ActionResult Index(string search, int? page, int? pagesize, int? idsearch)
        {
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            int defaSize = 10;
            if (pagesize != 0)
            {
                defaSize = (pagesize ?? 10);
            }

            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() {Value = "10", Text = "10"},
                new SelectListItem() {Value = "15", Text = "15"},
                new SelectListItem() {Value = "25", Text = "25"},
                new SelectListItem() {Value = "50", Text = "50"},
                new SelectListItem() {Value = "100", Text = "100"},
            };
            ViewBag.pagesize = defaSize;
            IPagedList<visa> passlist = null;
            passlist = db.visas.OrderBy(x => x.date_changed).ToPagedList(pageIndex, defaSize);
            var lists = new List<visa>();
            int j = 0;
            int i;
            var ab = db.visas.OrderBy(x => x.master_file.employee_no).ThenBy(x => x.date_changed).ToList();
            if (ab.Count != 0)
            {
                for (i = 0; i < ab.Count; i++)
                {
                    if (++j != ab.Count())
                    {
                        if (ab[i].emp_no == ab[j].emp_no)
                        {
                            continue;
                        }
                        else
                        {
                            lists.Add(ab[i]);
                        }
                    }
                }

                if (ab.Count != 1)
                {
                    if (ab[--j] != ab[i = i - 2])
                    {
                        lists.Add(ab[j]);
                    }
                }

                if (lists.Count == 0)
                {
                    i -= 1;
                    lists.Add(ab[i]);
                }
            }

            if (search != null)
            {
                lists.RemoveRange(0, lists.Count);
                j = 0;
                int idk;
                if (int.TryParse(search, out idk))
                {
                    ab = db.visas
                        .Where(x => x.master_file.employee_no.Equals(idk) /*.Contains(search) /*.StartsWith(search)*/)
                        .OrderBy(x => x.master_file.employee_no).ThenBy(x => x.date_changed)
                        .ToList();
                }
                else
                {
                    ab = db.visas
                        .Where(
                            x => x.master_file.employee_name
                                .Contains(search) /*.Contains(search) /*.StartsWith(search)*/)
                        .OrderBy(x => x.master_file.employee_no).ThenBy(x => x.date_changed).ToList();
                }

                if (ab.Count != 0)
                {
                    for (i = 0; i < ab.Count; i++)
                    {
                        if (++j != ab.Count())
                        {
                            if (ab[i].emp_no == ab[j].emp_no)
                            {
                                continue;
                            }
                            else
                            {
                                lists.Add(ab[i]);
                            }
                        }
                    }

                    if (ab.Count != 1)
                    {
                        if (ab[--j] != ab[i = i - 2])
                        {
                            lists.Add(ab[j]);
                        }
                    }

                    if (lists.Count == 0)
                    {
                        i -= 1;
                        lists.Add(ab[i]);
                    }
                }

                return View(lists.ToPagedList(page ?? 1, defaSize));
            }

            return View(lists.ToPagedList(page ?? 1, defaSize));
        }

        // GET: visas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            visa visa = db.visas.Find(id);
            if (visa == null)
            {
                return HttpNotFound();
            }

            return View(visa);
        }

        // GET: visas/Create
        [Authorize(Roles = "super_admin,admin,payrole,employee_VLC")]
        public ActionResult Create()
        {
            ViewBag.gender = new SelectList(db.Tables, "gender", "gender");
            ViewBag.emp_no = new SelectList(db.master_file.OrderBy(e => e.employee_no), "employee_id", "employee_no");
            ViewBag.emp_no1 =
                new SelectList(db.master_file.OrderBy(e => e.employee_name), "employee_id", "employee_name");
            return View();
        }

        // POST: visas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "super_admin,admin,payrole,employee_VLC")]
        public ActionResult Create(visa visa, HttpPostedFileBase fileBase)
        {
            string serverfile;
            if (fileBase != null)
            {
                var a = db.master_file.Find(visa.emp_no);
                var imgname = System.IO.Path.GetFileName(fileBase.FileName);
                var fileexe = System.IO.Path.GetExtension(fileBase.FileName);
                DirectoryInfo filepath = new DirectoryInfo("D:/HR/img/visa/" + fileexe);
                serverfile = "D:/HR/img/visa/" + a.employee_no; /*+ "/"+ passport.employee_no + fileexe;*/
                filepath = Directory.CreateDirectory(serverfile);
                int i = 0;
                do
                {
                    serverfile = "D:/HR/img/visa/" + a.employee_no + "/" + a.employee_no + "_" + i + fileexe;
                    i++;
                } while (System.IO.File.Exists(serverfile =
                    "D:/HR/img/visa/" + a.employee_no + "/" + a.employee_no + "_" + i + fileexe));

                fileBase.SaveAs(serverfile);
            }
            else

Views/visas/Create.cshtml
@model HRworks.Models.visa

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<script>
    function byidfill(parameters) {
        var filled = document.getElementById('fill');
        document.getElementById('hide2').style.display = "none";
        var x = document.getElementById("employee_no1");
        var y = document.getElementById("employee_no");
        y.value = x.value;
        document.getElementById('hide').style.display = "";
        var z = document.getElementById("demo");
        var w = document.getElementById("demo1");
        z.style.display = "";
        w.style.display = "none";
        myFunction();
    };

    function bynamefill(parameters) {
        document.getElementById('hide2').style.display = "";
        var x = document.getElementById("employee_no1");
        var y = document.getElementById("employee_no");
        x.value = y.value;
        document.getElementById('hide').style.display = "none";
        var z = document.getElementById("demo");
        var w = document.getElementById("demo1");
        w.style.display = "";
        z.style.display = "none";
        myFunction1();
    };

    var loadfile = function (event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('output');
            output.src = reader.result;
        };
        reader.readAsDataURL(event.target.files[0]);
    };

    function myFunction() {
        var x = document.getElementById("employee_no").value;
        document.getElementById("demo").innerHTML = "employee_id :" + x;

    };

    function myFunction1() {
        var x = document.getElementById("employee_no1").value;
        document.getElementById("demo").innerHTML = "employee_id :" + x;

    };
</script>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.14.1/jquery-ui.min.js"></script>
<script>
    $(function () {
        $("#datepicker").datepicker();
        $("#datepicker1").datepicker();
        $("#datepicker2").datepicker();
    });
</script>

@using (Html.BeginForm("Create", "visas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>visa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.uid_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uid_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uid_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emp_no, "employee_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4"
                 id="hide">
                @*
                    @Html.DropDownList("employee_no", null, htmlAttributes: new { @class = "form-control", @onchange="myfunction();" ,@id="employee_no"})*@
                @Html.DropDownList("emp_no", null, new { @class = "form-control", @id = "employee_no" })
                @Html.ValidationMessageFor(model => model.emp_no, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4"
                 id="hide2"
                 style="display: none">
                @*
                    @Html.DropDownList("employee_no", null, htmlAttributes: new { @class = "form-control", @onchange="myfunction();" ,@id="employee_no"})*@
                @Html.DropDownList("emp_no1", null, new { @class = "form-control", @id = "employee_no1" })
                @Html.ValidationMessageFor(model => model.emp_no, "", new { @class = "text-danger" })

            </div>

            <div class="col-md-6">
                <input type="button"
                       onclick="bynamefill()" @*ondblclick="byidfill()"*@
                       value="change to name"
                       id="demo" />
            </div>
            <div class="col-md-6">
                <input type="button"
                       onclick="byidfill()"
                       value="change to id"
                       style="display: none"
                       id="demo1" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.file_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.file_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.file_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.place_of_issue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.place_of_issue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.place_of_issue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.accompanied_by, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.accompanied_by, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.accompanied_by, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rv_expiry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rv_expiry, new { htmlAttributes = new { @class = "form-control", @id = "datepicker1" } })
                @Html.ValidationMessageFor(model => model.rv_expiry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rv_issue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rv_issue, new { htmlAttributes = new { @class = "form-control", @id = "datepicker1" } })
                @Html.ValidationMessageFor(model => model.rv_issue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.proff_as_per_visa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.proff_as_per_visa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.proff_as_per_visa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sponsor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sponsor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sponsor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <hr />
            <div class="row">

                @Html.LabelFor(model => model.imgpath, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    <input type="file"
                           id="fileBase"
                           style="display: none;"
                           accept="image/*" onchange="document.getElementById('test').innerHTML = 'file added'"
                           name="fileBase" />
                    <input type="button"
                           value="Upload"
                           onclick="document.getElementById('fileBase').click();" /><p id="test"></p>
                </div>
                <div class="col-md-5">
                </div>
            </div>
            <hr />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/visas/Delete.cshtml
@model HRworks.Models.visa

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>visa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.uid_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.uid_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.file_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.file_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.place_of_issue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.place_of_issue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.accompanied_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.accompanied_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rv_expiry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rv_expiry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rv_issue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rv_issue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.proff_as_per_visa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.proff_as_per_visa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imgpath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imgpath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sponsor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sponsor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.changed_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.changed_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_changed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_changed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.master_file.employee_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.master_file.employee_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/visas/Edit.cshtml
@model HRworks.Models.visa

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.14.1/jquery-ui.min.js"></script>
<script>
        $(function () {
            $("#datepicker").datepicker();
        });
        $(function () {
            $("#datepicker1").datepicker();
        });
        $(function () {
            $("#datepicker2").datepicker();
        });
</script>
<script>
        function byidfill(parameters) {
            var filled = document.getElementById('fill');
            document.getElementById('hide2').style.display = "none";
            var x = document.getElementById("employee_no1");
            var y = document.getElementById("employee_no");
            y.value = x.value;
            document.getElementById('hide').style.display = "";
            var z = document.getElementById("demo");
            var w = document.getElementById("demo1");
            z.style.display = "";
            w.style.display = "none";
            myFunction();
        };

        function bynamefill(parameters) {
            document.getElementById('hide2').style.display = "";
            var x = document.getElementById("employee_no1");
            var y = document.getElementById("employee_no");
            x.value = y.value;
            document.getElementById('hide').style.display = "none";
            var z = document.getElementById("demo");
            var w = document.getElementById("demo1");
            w.style.display = "";
            z.style.display = "none";
            myFunction1();
        };

        var loadfile = function(event) {
            var reader = new FileReader();
            reader.onload = function() {
                var output = document.getElementById('output');
                output.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
        };

        function myFunction() {
            var x = document.getElementById("employee_no").value;
            document.getElementById("demo").innerHTML = "employee_id :" + x;

        };

        function myFunction1() {
            var x = document.getElementById("employee_no1").value;
            document.getElementById("demo").innerHTML = "employee_id :" + x;

        };
</script>

@using (Html.BeginForm("Edit", "visas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>visa</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.employee_id)

    <div class="form-group">
        @Html.LabelFor(model => model.uid_no, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.uid_no, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.uid_no, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.emp_no, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.master_file.employee_no, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.EditorFor(model => model.emp_no, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @style = "display:none" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.file_no, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.file_no, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.file_no, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.place_of_issue, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.place_of_issue, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.place_of_issue, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.accompanied_by, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.accompanied_by, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.accompanied_by, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.rv_expiry, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.rv_expiry, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.rv_expiry, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.rv_issue, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.rv_issue, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.rv_issue, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.proff_as_per_visa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.proff_as_per_visa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.proff_as_per_visa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.sponsor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sponsor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sponsor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <hr />
        <div class="row">

            @Html.LabelFor(model => model.imgpath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                <input type="file"
                       id="fileBase"
                       style="display: none;"
                       accept="image/*" onchange="document.getElementById('test').innerHTML = 'file added'"
                       name="fileBase" />
                <input type="button"
                       value="Upload"
                       onclick="document.getElementById('fileBase').click();" /><p id="test"></p>
            </div>
            <div class="col-md-5">
            </div>
        </div>
        <hr />
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}