Controllers/uploaddataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using HRworks.Models;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.CodeAnalysis;
using Microsoft.Office.Interop.Word;
using OfficeOpenXml;
using static iText.StyledXmlParser.Jsoup.Select.Evaluator;

namespace HRworks.Controllers
{
    [Authorize]
    public class uploaddataController : Controller
    {
        private const string Purpose = "equalizer";

        public string Protect(string unprotectedText)
        {
            if (unprotectedText.IsNullOrWhiteSpace())
            {
                unprotectedText = "0";
            }

            var unprotectedBytes = Encoding.UTF8.GetBytes(unprotectedText);
            var protectedBytes = MachineKey.Protect(unprotectedBytes, Purpose);
            var protectedText = Convert.ToBase64String(protectedBytes);
            return protectedText;
        }

        public string Unprotect(string protectedText)
        {
            try
            {
                var protectedBytes = Convert.FromBase64String(protectedText);
                var unprotectedBytes = MachineKey.Unprotect(protectedBytes, Purpose);
                var unprotectedText = Encoding.UTF8.GetString(unprotectedBytes);
                return unprotectedText;
            }
            catch (Exception ex)
            {
                return string.Empty;
            }
        }

        private readonly HREntities db = new HREntities();

        // GET: uploaddata
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Importincl()
        {
            return this.View();
        }

        [ActionName("Importincl")]
        [HttpPost]
        public ActionResult ImportIncl()
        {
            if (this.Request.Files["FileUpload1"].ContentLength > 0)
            {
                var extension = Path.GetExtension(this.Request.Files["FileUpload1"].FileName).ToLower();
                string query = null;
                var connString = string.Empty;

                string[] validFileTypes = { ".csv" };

                var path1 = string.Format(
                    "{0}/{1}",
                    this.Server.MapPath("~/Content/Uploads"),
                    this.Request.Files["FileUpload1"].FileName);
                if (!Directory.Exists(path1)) Directory.CreateDirectory(this.Server.MapPath("~/Content/Uploads"));
                var alist = this.db.master_file.OrderBy(e => e.employee_no).ThenByDescending(x => x.date_changed)
                    .ToList();
                var afinallist = new List<master_file>();
                foreach (var file in alist)
                {
                    if (afinallist.Count == 0) afinallist.Add(file);

                    if (!afinallist.Exists(x => x.employee_no == file.employee_no)) afinallist.Add(file);
                }

                if (validFileTypes.Contains(extension))
                {
                    if (System.IO.File.Exists(path1)) System.IO.File.Delete(path1);

                    this.Request.Files["FileUpload1"].SaveAs(path1);
                    if (extension == ".csv")
                    {
                        var dt = Utility.ConvertCSVtoDataTable(path1);
                        this.ViewBag.Data = dt;
                        if (dt.Rows.Count > 0)
                        {
                            var leavecheck = this.db.contracts.ToList();
                            foreach (DataRow dr in dt.Rows)
                            {
                                var pro = new insurance();
                                foreach (DataColumn column in dt.Columns)
                                {
                                    if (dr[column] == null || dr[column].ToString() == " ") goto e;

                                    if (column.ColumnName == "Card no")
                                    {
                                        var dtt = dr[column].ToString();
                                        int.TryParse(dtt, out var a);
                                        pro.card_no = a;
                                    }

                                    if (column.ColumnName == "Dependency")
                                    {
                                        var dtt = dr[column].ToString();
                                        pro.dependency = dtt;
                                    }

                                    if (column.ColumnName == "Marital Status")
                                    {
                                        var dtt = dr[column].ToString();
                                        pro.marital_status = dtt;
                                    }

                                    if (column.ColumnName == "Annual Primium")
                                    {
                                        var dtt = dr[column].ToString();
                                        int.TryParse(dtt, out var a);
                                        pro.annual_primium = a;
                                    }

                                    if (column.ColumnName == "Invoice No")
                                    {
                                        var dtt = dr[column].ToString();
                                        int.TryParse(dtt, out var a);
                                        pro.invoice_no = a;
                                    }


                                    if (column.ColumnName == "Credit Amt")
                                    {
                                        var dtt = dr[column].ToString();
                                        int.TryParse(dtt, out var a);
                                        pro.credit_amt = a;
                                    }

                                    if (column.ColumnName == "Deletion Date")
                                    {
                                        var dtt = dr[column].ToString();
                                        DateTime.TryParse(dtt, out var a);
                                        pro.deletion_date = a;
                                    }


                                    if (column.ColumnName == "employee_no")
                                    {
                                        int.TryParse(dr[column].ToString(), out var idm);
                                        if (idm != 0)
                                        {
                                            var epid = afinallist.Find(x => x.employee_no == idm);
                                            if (epid == null) goto e;
                                            pro.employee_no = epid.employee_id;
                                            var dob = epid.dob.Value;
                                            var age = 0;
                                            age = DateTime.Now.DayOfYear - dob.Year;
                                            if (DateTime.Now.DayOfYear < dob.DayOfYear)
                                                age = age - 1;
                                            pro.age = age;
                                        }
                                    }
                                }

                                this.db.insurances.Add(pro);
                                this.db.SaveChanges();
                                e: ;
                            }
                        }
                    }
                }
            }
            else
            {
                this.ViewBag.Error = "Please Upload Files in .csv format";
            }

            return this.View();
        }


        public ActionResult Importbankdetails()
        {
            return this.View();
        }

        [ActionName("Importbankdetails")]
        [HttpPost]
        public ActionResult ImportbankDetails()
        {
            if (this.Request.Files["FileUpload1"].ContentLength > 0)
            {
                var extension = Path.GetExtension(this.Request.Files["FileUpload1"].FileName).ToLower();
                string query = null;
                var connString = string.Empty;

                string[] validFileTypes = { ".csv" };

                var path1 = string.Format(
                    "{0}/{1}",
                    this.Server.MapPath("~/Content/Uploads"),
                    this.Request.Files["FileUpload1"].FileName);
                if (!Directory.Exists(path1)) Directory.CreateDirectory(this.Server.MapPath("~/Content/Uploads"));
                var alist = this.db.master_file.OrderBy(e => e.employee_no).ThenByDescending(x => x.date_changed)
                    .ToList();
                var afinallist = new List<master_file>();
                foreach (var file in alist)
                {
                    if (afinallist.Count == 0) afinallist.Add(file);

                    if (!afinallist.Exists(x => x.employee_no == file.employee_no)) afinallist.Add(file);
                }

                if (validFileTypes.Contains(extension))
                {
                    if (System.IO.File.Exists(path1)) System.IO.File.Delete(path1);

                    this.Request.Files["FileUpload1"].SaveAs(path1);
                    if (extension == ".csv")
                    {
                        var dt = Utility.ConvertCSVtoDataTable(path1);
                        this.ViewBag.Data = dt;
                        if (dt.Rows.Count > 0)
                        {
                            foreach (DataRow dr in dt.Rows)
                            {
                                var pro = new bank_details();
                                foreach (DataColumn column in dt.Columns)
                                {

Views/uploaddata/Empnochange.cshtml
@using System.Data;
@{
    ViewBag.Title = "Emp Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Emp Update</h2>
<!--[if !IE]><!-->
<style type="text/css">


    /* Generic Styling, for Desktops/Laptops */
    table {
        width: 100%;
        border-collapse: collapse;
    }

    /* Zebra striping */

    tr:nth-of-type(odd) {
        background: #eee;
    }

    th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    td, th {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }

    /*
    Max width before this PARTICULAR table gets nasty
    This query will take effect for any screen smaller than 760px
    and also iPads specifically.
    */

    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        /* Force table to not be like tables anymore */
        table, thead, tbody, th, td, tr {
            display: block;
        }
            /* Hide table headers (but not display: none;, for accessibility) */
            thead tr {
                position: absolute;
                top: -9999px;
                left: -9999px;
            }

        tr {
            border: 1px solid #ccc;
        }

        td {
            /* Behave  like a "row" */
            border: none;
            border-bottom: 1px solid #eee;
            position: relative;
            padding-left: 50%;
        }

            td:before {
                /* Now like a table header */
                position: absolute;
                /* Top/left values mimic padding */
                top: 6px;
                left: 6px;
                width: 45%;
                padding-right: 10px;
                white-space: nowrap;
            }
            /*
     Label the data
                <input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Downloadincsample")'" value="download incsample" />
     */
            td:before {
                content: attr(data-title);
            }
    }
</style>

<!--<![endif]-->
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Index")'" value=" back to main" />
@ViewBag.masternotuploaded
<br />
@using (Html.BeginForm("Empnochange", "uploaddata", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    <table>
        <tr>
            <td>Excel file</td>
            <td>
                <input type="file" id="FileUpload1" name="FileUpload1" />
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" id="Submit" name="Submit" value="Submit" />
            </td>
        </tr>
    </table>
}

<div>
    <table id="">

        @if (ViewBag.Data != null)
        {
            <thead>

                @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                {
                <th>@column.ColumnName.ToUpper()</th>
            }
                </thead>
                if ((ViewBag.Data as System.Data.DataTable).Rows.Count > 0)
                {
                    foreach (DataRow dr in (ViewBag.Data as System.Data.DataTable).Rows)
                    {
                        <tr>

                            @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                            {
                                <td data-title='@column.ColumnName'>

                                    @dr[column].ToString()
                                </td>
                            }




                        </tr>
                    }
                }
                else
                {
                    int count = (ViewBag.Data as System.Data.DataTable).Columns.Count;
                    <tr>

                        <td colspan='@count' style="color: red;">

                            No Data Found.
                        </td>


                    </tr>
                }
            }
            else
            {
                if (ViewBag.Error != null)
                {
                    <tr>
                        <td style="color: red;">

                            @(ViewBag.Error != null ? ViewBag.Error.ToString() : "")
                        </td>


                    </tr>
                }
            }
    </table>
</div>

Views/uploaddata/ImportbankDetails.cshtml
@using System.Data;
@{
    ViewBag.Title = "ImportExcel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ImportExcel</h2>
<!--[if !IE]><!-->
<style type="text/css">


    /* Generic Styling, for Desktops/Laptops */
    table {
        width: 100%;
        border-collapse: collapse;
    }

    /* Zebra striping */

    tr:nth-of-type(odd) {
        background: #eee;
    }

    th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    td, th {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }

    /*
    Max width before this PARTICULAR table gets nasty
    This query will take effect for any screen smaller than 760px
    and also iPads specifically.
    */

    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        /* Force table to not be like tables anymore */
        table, thead, tbody, th, td, tr {
            display: block;
        }
            /* Hide table headers (but not display: none;, for accessibility) */
            thead tr {
                position: absolute;
                top: -9999px;
                left: -9999px;
            }

        tr {
            border: 1px solid #ccc;
        }

        td {
            /* Behave  like a "row" */
            border: none;
            border-bottom: 1px solid #eee;
            position: relative;
            padding-left: 50%;
        }

            td:before {
                /* Now like a table header */
                position: absolute;
                /* Top/left values mimic padding */
                top: 6px;
                left: 6px;
                width: 45%;
                padding-right: 10px;
                white-space: nowrap;
            }
            /*
     Label the data
                <input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Downloadincsample")'" value="download incsample" />
     */
            td:before {
                content: attr(data-title);
            }
    }
</style>

<!--<![endif]-->
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Index")'" value=" back to main" />

<br />
@using (Html.BeginForm("Importbankdetails", "uploaddata", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    <table>
        <tr>
            <td>Excel file</td>
            <td>
                <input type="file" id="FileUpload1" name="FileUpload1" />
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" id="Submit" name="Submit" value="Submit" />
            </td>
        </tr>
    </table>
}

<div>
    <table id="">

        @if (ViewBag.Data != null)
        {
            <thead>

                @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                {
                <th>@column.ColumnName.ToUpper()</th>
            }
                </thead>
                if ((ViewBag.Data as System.Data.DataTable).Rows.Count > 0)
                {
                    foreach (DataRow dr in (ViewBag.Data as System.Data.DataTable).Rows)
                    {
                        <tr>

                            @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                            {
                                <td data-title='@column.ColumnName'>

                                    @dr[column].ToString()
                                </td>
                            }




                        </tr>
                    }
                }
                else
                {
                    int count = (ViewBag.Data as System.Data.DataTable).Columns.Count;
                    <tr>

                        <td colspan='@count' style="color: red;">

                            No Data Found.
                        </td>


                    </tr>
                }
            }
            else
            {
                if (ViewBag.Error != null)
                {
                    <tr>
                        <td style="color: red;">

                            @(ViewBag.Error != null ? ViewBag.Error.ToString() : "")
                        </td>


                    </tr>
                }
            }
    </table>
</div>

Views/uploaddata/Importconlcbdppeid.cshtml
@using System.Data
@{
    ViewBag.Title = "Importconlcbdppeid";
}

<h2>UPLOAD DATA</h2>


<!--[if !IE]><!-->
<style type="text/css">


    /* Generic Styling, for Desktops/Laptops */
    table {
        width: 100%;
        border-collapse: collapse;
    }

    /* Zebra striping */

    tr:nth-of-type(odd) {
        background: #eee;
    }

    th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    td, th {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }

    /*
    Max width before this PARTICULAR table gets nasty
    This query will take effect for any screen smaller than 760px
    and also iPads specifically.
    */

    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        /* Force table to not be like tables anymore */
        table, thead, tbody, th, td, tr {
            display: block;
        }
            /* Hide table headers (but not display: none;, for accessibility) */
            thead tr {
                position: absolute;
                top: -9999px;
                left: -9999px;
            }

        tr {
            border: 1px solid #ccc;
        }

        td {
            /* Behave  like a "row" */
            border: none;
            border-bottom: 1px solid #eee;
            position: relative;
            padding-left: 50%;
        }

            td:before {
                /* Now like a table header */
                position: absolute;
                /* Top/left values mimic padding */
                top: 6px;
                left: 6px;
                width: 45%;
                padding-right: 10px;
                white-space: nowrap;
            }
            /*
     Label the data
                <input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Downloadincsample")'" value="download incsample" />
     */
            td:before {
                content: attr(data-title);
            }
    }
</style>

<!--<![endif]-->
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Index")'" value=" back to main" />
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Downloadallsample")'" value="download sample" />

<br />
@using (Html.BeginForm("Importbankdetails", "uploaddata", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    <table>
        <tr>
            <td>Excel file</td>
            <td>
                <input type="file" id="FileUpload1" name="FileUpload1" />
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" id="Submit" name="Submit" value="Submit" />
            </td>
        </tr>
    </table>
}

<div>
    <table id="">

        @if (ViewBag.Data != null)
        {
            <thead>

                @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                {
                <th>@column.ColumnName.ToUpper()</th>
            }
                </thead>
                if ((ViewBag.Data as System.Data.DataTable).Rows.Count > 0)
                {
                    foreach (DataRow dr in (ViewBag.Data as System.Data.DataTable).Rows)
                    {
                        <tr>

                            @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                            {
                                <td data-title='@column.ColumnName'>

                                    @dr[column].ToString()
                                </td>
                            }




                        </tr>
                    }
                }
                else
                {
                    int count = (ViewBag.Data as System.Data.DataTable).Columns.Count;
                    <tr>

                        <td colspan='@count' style="color: red;">

                            No Data Found.
                        </td>


                    </tr>
                }
            }
            else
            {
                if (ViewBag.Error != null)
                {
                    <tr>
                        <td style="color: red;">

                            @(ViewBag.Error != null ? ViewBag.Error.ToString() : "")
                        </td>


                    </tr>
                }
            }
    </table>
</div>

Views/uploaddata/Importincl.cshtml
@using System.Data;
@{
    ViewBag.Title = "ImportExcel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ImportExcel</h2>
<!--[if !IE]><!-->
<style type="text/css">


    /* Generic Styling, for Desktops/Laptops */
    table {
        width: 100%;
        border-collapse: collapse;
    }

    /* Zebra striping */

    tr:nth-of-type(odd) { background: #eee; }

    th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    td, th {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }

    /*
    Max width before this PARTICULAR table gets nasty
    This query will take effect for any screen smaller than 760px
    and also iPads specifically.
    */

    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        /* Force table to not be like tables anymore */
        table, thead, tbody, th, td, tr { display: block; }

        /* Hide table headers (but not display: none;, for accessibility) */
        thead tr {
            position: absolute;
            top: -9999px;
            left: -9999px;
        }

        tr { border: 1px solid #ccc; }

        td {
            /* Behave  like a "row" */
            border: none;
            border-bottom: 1px solid #eee;
            position: relative;
            padding-left: 50%;
        }

        td:before {
            /* Now like a table header */
            position: absolute;
            /* Top/left values mimic padding */
            top: 6px;
            left: 6px;
            width: 45%;
            padding-right: 10px;
            white-space: nowrap;
        }

        /*
     Label the data
     */
        td:before { content: attr(data-title); }
    }
</style>

<!--<![endif]-->
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Index")'" value=" back to main"/>
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Downloadincsample")'" value="download incsample"/>
<br/>
@using (Html.BeginForm("importincl", "uploaddata", FormMethod.Post, new {enctype = "multipart/form-data"}))

{
    <table>
        <tr>
            <td>Excel file</td>
            <td>
                <input type="file" id="FileUpload1" name="FileUpload1"/>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" id="Submit" name="Submit" value="Submit"/>
            </td>
        </tr>
    </table>
}

<div>
    <table id="">

        @if (ViewBag.Data != null)
        {
            <thead>

            @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
            {
                <th>@column.ColumnName.ToUpper()</th>
            }
            </thead>
            if ((ViewBag.Data as System.Data.DataTable).Rows.Count > 0)
            {
                foreach (DataRow dr in (ViewBag.Data as System.Data.DataTable).Rows)
                {
                    <tr>

                        @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                        {
                            <td data-title='@column.ColumnName'>

                                @dr[column].ToString()
                            </td>
                        }




                    </tr>
                }
            }
            else
            {
                int count = (ViewBag.Data as System.Data.DataTable).Columns.Count;
                <tr>

                    <td colspan='@count' style="color: red;">

                        No Data Found.
                    </td>


                </tr>
            }
        }
        else
        {
            if (ViewBag.Error != null)
            {
                <tr>
                    <td style="color: red;">

                        @(ViewBag.Error != null ? ViewBag.Error.ToString() : "")
                    </td>


                </tr>
            }
        }
    </table>
</div>

Views/uploaddata/Importlaborcard.cshtml
@using System.Data
@{
    ViewBag.Title = "upload labor card";
}


<h2>UPLOAD DATA</h2>


<!--[if !IE]><!-->
<style type="text/css">


    /* Generic Styling, for Desktops/Laptops */
    table {
        width: 100%;
        border-collapse: collapse;
    }

    /* Zebra striping */

    tr:nth-of-type(odd) {
        background: #eee;
    }

    th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    td, th {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }

    /*
    Max width before this PARTICULAR table gets nasty
    This query will take effect for any screen smaller than 760px
    and also iPads specifically.
    */

    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        /* Force table to not be like tables anymore */
        table, thead, tbody, th, td, tr {
            display: block;
        }
            /* Hide table headers (but not display: none;, for accessibility) */
            thead tr {
                position: absolute;
                top: -9999px;
                left: -9999px;
            }

        tr {
            border: 1px solid #ccc;
        }

        td {
            /* Behave  like a "row" */
            border: none;
            border-bottom: 1px solid #eee;
            position: relative;
            padding-left: 50%;
        }

            td:before {
                /* Now like a table header */
                position: absolute;
                /* Top/left values mimic padding */
                top: 6px;
                left: 6px;
                width: 45%;
                padding-right: 10px;
                white-space: nowrap;
            }
            td:before {
                content: attr(data-title);
            }
    }
</style>

<!--<![endif]-->
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Index")'" value=" back to main" />
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Downloadlaborsample")'" value="download sample" />

<br />
@using (Html.BeginForm("Importlaborcard", "uploaddata", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    <table>
        <tr>
            <td>Excel file</td>
            <td>
                <input type="file" id="FileUpload1" name="FileUpload1" />
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" id="Submit" name="Submit" value="Submit" />
            </td>
        </tr>
    </table>
}

<div>
    <table id="">

        @if (ViewBag.Data != null)
        {
            <thead>

                @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                {
                <th>@column.ColumnName.ToUpper()</th>
            }
                </thead>
                if ((ViewBag.Data as System.Data.DataTable).Rows.Count > 0)
                {
                    foreach (DataRow dr in (ViewBag.Data as System.Data.DataTable).Rows)
                    {
                        <tr>

                            @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                            {
                                <td data-title='@column.ColumnName'>

                                    @dr[column].ToString()
                                </td>
                            }




                        </tr>
                    }
                }
                else
                {
                    int count = (ViewBag.Data as System.Data.DataTable).Columns.Count;
                    <tr>

                        <td colspan='@count' style="color: red;">

                            No Data Found.
                        </td>


                    </tr>
                }
            }
            else
            {
                if (ViewBag.Error != null)
                {
                    <tr>
                        <td style="color: red;">

                            @(ViewBag.Error != null ? ViewBag.Error.ToString() : "")
                        </td>


                    </tr>
                }
            }
    </table>
</div>