Models/emprel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emprel
    {
        public int Id { get; set; }
        public int Employee_id { get; set; }
        public int line_man { get; set; }
        public Nullable<int> HOD { get; set; }
    
        public virtual master_file master_file { get; set; }
        public virtual master_file master_file1 { get; set; }
        public virtual master_file master_file2 { get; set; }
    }
}

Controllers/emprelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HRworks.Models;
using Microsoft.Ajax.Utilities;
using OfficeOpenXml;
using Excel = Microsoft.Office.Interop.Excel;

namespace HRworks.Controllers
{
    [Authorize(Roles = "employee_rel,super_admin")]
    public class emprelsController : Controller
    {
        private HREntities db = new HREntities();

        // GET: emprels
        public ActionResult Index()
        {
            var emprels = db.emprels.Include(e => e.master_file).Include(e => e.master_file1).Include(e => e.master_file2).ToList();
            return View(emprels.OrderBy(x=>x.master_file1.employee_no));
        }

        // GET: emprels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            emprel emprel = db.emprels.Find(id);
            if (emprel == null)
            {
                return HttpNotFound();
            }
            return View(emprel);
        }

        // GET: emprels/Create
        public ActionResult Create()
        {
            var empmodels = new master_fileController();
            var afinallist = empmodels.emplist();
            ViewBag.HOD = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid");
            ViewBag.Employee_id = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid");
            ViewBag.line_man = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid");
            return View();
        }

        // POST: emprels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Employee_id,line_man,HOD")] emprel emprel)
        {
            if (ModelState.IsValid)
            {
                var dublicatecheck = this.db.emprels.ToList();
                if (!dublicatecheck.Exists(x =>
                    x.Employee_id == emprel.Employee_id && x.line_man == emprel.line_man &&
                    x.HOD == emprel.HOD))
                {
                    this.db.emprels.Add(emprel);
                    this.db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            var empmodels = new master_fileController();
            var afinallist = empmodels.emplist();
            ViewBag.HOD = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid", emprel.HOD);
            ViewBag.Employee_id = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid", emprel.Employee_id);
            ViewBag.line_man = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid", emprel.line_man);
            return View(emprel);
        }

        // GET: emprels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            emprel emprel = db.emprels.Find(id);
            if (emprel == null)
            {
                return HttpNotFound();
            }

            var empmodels = new master_fileController();
            var afinallist = empmodels.emplist();
            ViewBag.HOD = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid", emprel.HOD);
            ViewBag.Employee_id = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid", emprel.Employee_id);
            ViewBag.line_man = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid", emprel.line_man);
            return View(emprel);
        }

        // POST: emprels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Employee_id,line_man,HOD")] emprel emprel)
        {
            if (ModelState.IsValid)
            {/*
                var emp =this.db.master_file.Find(emprel.Employee_id);
                var empLM =this.db.master_file.Find(emprel.line_man);
                var empHOD = new master_file();
                empHOD = null;
                if (emprel.HOD != null)
                { 
                    empHOD = this.db.master_file.Find(emprel.HOD);
                }*/
                var dublicatecheck = this.db.emprels.ToList();
                if (!dublicatecheck.Exists(x =>
                    x.Employee_id == emprel.Employee_id && x.line_man == emprel.line_man &&
                    x.HOD == emprel.HOD))
                {
                    var attachedEntity = db.emprels.Find(emprel.Id);
                    if (attachedEntity != null && db.Entry(attachedEntity).State != EntityState.Detached)
                    {
                        db.Entry(attachedEntity).State = EntityState.Detached;
                    }
                    db.Entry(emprel).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            var empmodels = new master_fileController();
            var afinallist = empmodels.emplist();
            ViewBag.HOD = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid", emprel.HOD);
            ViewBag.Employee_id = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid", emprel.Employee_id);
            ViewBag.line_man = new SelectList(afinallist.OrderBy(x => x.employee_no), "employee_id", "emiid", emprel.line_man);
            return View(emprel);
        }

        // GET: emprels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            emprel emprel = db.emprels.Find(id);
            if (emprel == null)
            {
                return HttpNotFound();
            }
            return View(emprel);
        }

        // POST: emprels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            emprel emprel = db.emprels.Find(id);
            db.emprels.Remove(emprel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [ActionName("Importexcel")]
        [HttpPost]
        public ActionResult Importexcel()
        {
            if (this.Request.Files["FileUpload1"].ContentLength > 0)
            {
                var extension = Path.GetExtension(this.Request.Files["FileUpload1"].FileName).ToLower();
                string query = null;
                var connString = string.Empty;

                string[] validFileTypes = { ".csv" };

                var path1 = string.Format(
                    "{0}/{1}",
                    this.Server.MapPath("~/Content/Uploads"),
                    this.Request.Files["FileUpload1"].FileName);
                if (!Directory.Exists(path1)) Directory.CreateDirectory(this.Server.MapPath("~/Content/Uploads"));
                var alist = this.db.master_file.OrderBy(e => e.employee_no).ThenByDescending(x => x.date_changed)
                    .ToList();
                var afinallist = new List<master_file>();
                var erlist = new List<emprel>();
                foreach (var file in alist)
                {
                    if (afinallist.Count == 0) afinallist.Add(file);

                    if (!afinallist.Exists(x => x.employee_no == file.employee_no)) afinallist.Add(file);
                }

                if (validFileTypes.Contains(extension))
                {
                    if (System.IO.File.Exists(path1)) System.IO.File.Delete(path1);

                    this.Request.Files["FileUpload1"].SaveAs(path1);
                    if (extension == ".csv")
                    {
                        var dt = Utility.ConvertCSVtoDataTable(path1);
                        this.ViewBag.Data = dt;
                        if (dt.Rows.Count > 0)
                        {
                            var br = 0;
                            var bebr = 0;
                            foreach (DataRow dr in dt.Rows)
                            {
                                if (bebr >= 3)
                                {
                                    bebr = 0;
                                    br++;
                                }

                                if (br > 1)
                                {
                                    goto brgoto;
                                }
                                var pro = new emprel();
                                var dublicatecheck = this.db.emprels.ToList();
                                foreach (DataColumn column in dt.Columns)
                                {

                                    if (dr[column].ToString().IsNullOrWhiteSpace())
                                    {
                                        bebr++;
                                    }
                                    else
                                    {
                                        if (bebr != 0)
                                        {
                                            bebr--;
                                        }
                                    }
                                    if (column.ColumnName == "employee no")

Views/emprels/Create.cshtml
@model HRworks.Models.emprel

@{
    ViewBag.Title = "Create";
}


<link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.14.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
        $(function () {
            $("#Employee_id").chosen({ no_results_text: "Oops, nothing found!" });
            $("#HOD").chosen({ no_results_text: "Oops, nothing found!" });
            $("#line_man").chosen({ no_results_text: "Oops, nothing found!" });
        });

        function humanise(diff) {
            // The string we're working with to create the representation
            var str = '';
            // Map lengths of `diff` to different time periods
            var values = [[' year', 365], [' month', 30], [' day', 1]];
            // Iterate over the values...
            for (var i = 0; i < values.length; i++) {
                var amount = Math.floor(diff / values[i][1]);
                // ... and find the largest time value that fits into the diff
                if (amount >= 1) {
                    // If we match, add to the string ('s' is for pluralization)
                    str += amount + values[i][0] + (amount > 1 ? 's' : '') + ' ';

                    // and subtract from the diff
                    diff -= amount * values[i][1];
                }
            }
            return str;
        }
    </script>
<h2>employee relations</h2>
<h4>Create</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Employee_id, "Employee_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Employee_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Employee_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.line_man, "line_man", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("line_man", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.line_man, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HOD, "HOD", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HOD", null,"", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HOD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/emprels/Delete.cshtml
@model HRworks.Models.emprel

@{
    ViewBag.Title = "Delete";
}

<h2>employee relations</h2>
<h4>Delete</h4>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            HOD/GM
        </dt>

        <dd>
            @Html.DisplayFor(model => model.master_file.employee_name)
        </dd>

        <dt>
            line manager
        </dt>

        <dd>
            @Html.DisplayFor(model => model.master_file2.employee_name)
        </dd>
        <dt>
            employee
        </dt>

        <dd>
            @Html.DisplayFor(model => model.master_file1.employee_name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/emprels/Details.cshtml
@model HRworks.Models.emprel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>emprel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.master_file.employee_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.master_file.employee_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.master_file1.employee_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.master_file1.employee_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.master_file2.employee_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.master_file2.employee_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/emprels/Edit.cshtml
@model HRworks.Models.emprel

@{
    ViewBag.Title = "Edit";
}


<link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.14.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
        $(function () {
            $("#Employee_id").chosen({ no_results_text: "Oops, nothing found!" });
            $("#HOD").chosen({
                no_results_text: "Oops, nothing found!",
                allow_single_deselect: true
});
            $("#line_man").chosen({ no_results_text: "Oops, nothing found!" });
        });

        function humanise(diff) {
            // The string we're working with to create the representation
            var str = '';
            // Map lengths of `diff` to different time periods
            var values = [[' year', 365], [' month', 30], [' day', 1]];
            // Iterate over the values...
            for (var i = 0; i < values.length; i++) {
                var amount = Math.floor(diff / values[i][1]);
                // ... and find the largest time value that fits into the diff
                if (amount >= 1) {
                    // If we match, add to the string ('s' is for pluralization)
                    str += amount + values[i][0] + (amount > 1 ? 's' : '') + ' ';

                    // and subtract from the diff
                    diff -= amount * values[i][1];
                }
            }
            return str;
        }
</script>
<h2>employee relations</h2>
<h4>Edit</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Employee_id, "Employee_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Employee_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Employee_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.line_man, "line_man", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("line_man", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.line_man, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HOD, "HOD", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HOD", null, "", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HOD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/emprels/Importexcel.cshtml
@using System.Data;
@{
    ViewBag.Title = "ImportExcel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ImportExcel</h2>
<!--[if !IE]><!-->
<style type="text/css">


    /* Generic Styling, for Desktops/Laptops */
    table {
        width: 100%;
        border-collapse: collapse;
    }
    /* Zebra striping */
    tr:nth-of-type(odd) {
        background: #eee;
    }

    th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    td, th {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }
    /*
    Max width before this PARTICULAR table gets nasty
    This query will take effect for any screen smaller than 760px
    and also iPads specifically.
    */
    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        /* Force table to not be like tables anymore */
        table, thead, tbody, th, td, tr {
            display: block;
        }
            /* Hide table headers (but not display: none;, for accessibility) */
            thead tr {
                position: absolute;
                top: -9999px;
                left: -9999px;
            }

        tr {
            border: 1px solid #ccc;
        }

        td {
            /* Behave  like a "row" */
            border: none;
            border-bottom: 1px solid #eee;
            position: relative;
            padding-left: 50%;
        }

            td:before {
                /* Now like a table header */
                position: absolute;
                /* Top/left values mimic padding */
                top: 6px;
                left: 6px;
                width: 45%;
                padding-right: 10px;
                white-space: nowrap;
            }
            /*
     Label the data
     */
            td:before {
                content: attr(data-title);
            }
    }
</style>

<!--<![endif]-->
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Index")'" value="back to main" />
<input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("DownloadExcel")'" value="download template" />
<br />
@using (Html.BeginForm("ImportExcel", "emprels", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr><td>Excel file</td><td><input type="file" id="FileUpload1" name="FileUpload1" /></td></tr>
        <tr><td></td><td><input type="submit" id="Submit" name="Submit" value="Submit" /></td></tr>
    </table>
}

<div>
    <table id="">

        @if (ViewBag.Data != null)
        {
            <thead>

                @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                {
                <th>@column.ColumnName.ToUpper()</th>





            }
                </thead>
                if ((ViewBag.Data as System.Data.DataTable).Rows.Count > 0)
                {
                    foreach (DataRow dr in (ViewBag.Data as System.Data.DataTable).Rows)
                    {

                        <tr>

                            @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                            {
                                <td data-title='@column.ColumnName'>

                                    @dr[column].ToString()
                                </td>

                            }




                        </tr>



                    }

                }
                else
                {
                    int count = (ViewBag.Data as System.Data.DataTable).Columns.Count;
                    <tr>

                        <td colspan='@count' style="color:red;">

                            No Data Found.
                        </td>



                    </tr>



                }

            }
            else
            {
                if (ViewBag.Error != null)
                {
                    <tr>
                        <td style="color:red;">

                            @(ViewBag.Error != null ? ViewBag.Error.ToString() : "")
                        </td>



                    </tr>

                }
            }
    </table>
</div>

Views/emprels/Index.cshtml
@using Microsoft.Ajax.Utilities
@model IEnumerable<HRworks.Models.emprel>

@{
    ViewBag.Title = "Index";
}

<h2>employee relations</h2>

<p>
    <div>
        <input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("Create", "emprels")'" value="Create new"/>
        <input type="button" class="btn btn-default" onclick="window.location.href = '@Url.Action("ImportExcel", "emprels")'" value="Upload"/>
    </div>
</p>
<table class="table">
    <tr>
        <th colspan="2">employee</th>
        <th colspan="2">line manager</th>
        <th colspan="2">HOD/GM</th>
        <th></th>
    </tr>
    <tr>
        <th>
            employee no
        </th>
        <th>
            name
        </th>
        <th>
            employee no
        </th>
        <th>
            name
        </th>
        <th>
            employee no
        </th>
        <th>
            name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.master_file1.emiid.IsNullOrWhiteSpace())
                {
                    @Html.DisplayFor(modelItem => item.master_file1.employee_no)
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.master_file1.emiid)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.master_file1.employee_name)
            </td>
            <td>
                @if (item.master_file2.emiid.IsNullOrWhiteSpace())
                {
                    @Html.DisplayFor(modelItem => item.master_file2.employee_no)
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.master_file2.emiid)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.master_file2.employee_name)
            </td>
            <td>
                @if (item.master_file != null)
                {
                    if (item.master_file.emiid.IsNullOrWhiteSpace())
                    {
                        @Html.DisplayFor(modelItem => item.master_file.employee_no)
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.master_file.emiid)
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.master_file.employee_name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Views/emprels/NoRel.cshtml
@model IEnumerable<HRworks.Models.master_file>

@{
    ViewBag.Title = "NoRel";
    var i = 0;
}

<h2>No Relations/Workflows </h2>

<table class="table">
	<tr>
        <th>SR#</th>
		<th>
			@Html.DisplayNameFor(model => model.employee_no)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.employee_name)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.date_joined)
		</th>
	</tr>

@foreach (var item in Model) {
		<tr>
        <td>@{
	            i++;
				@i;
            }</td>
		<td>
			@Html.DisplayFor(modelItem => item.emiid)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.employee_name)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.date_joined)
		</td>
	</tr>
}

</table>